"""Removing participant email

Revision ID: 04979e5673df
Revises: f8f7816d987b
Create Date: 2025-02-01 15:16:35.618479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04979e5673df'
down_revision = 'f8f7816d987b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('committee')
        batch_op.drop_column('school')
        batch_op.drop_column('email')
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('school', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('committee', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
