"""Added scheduling to Message model

Revision ID: 97db1229c6f1
Revises: 04979e5673df
Create Date: 2025-02-05 15:22:06.681988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97db1229c6f1'
down_revision = '04979e5673df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('scheduled_at')

    # ### end Alembic commands ###
